/**
 * Created by panda on 12/06/2015.
 */
var fs = require('fs');
var md5 = require('MD5');
var walk    = require('walk');

var output   = "//AUTOGENERATED\r\nangular.module('angularApp.base').constant('map_hash', { \r\n";


var folder = 'games';

var walker  = walk.walk(folder, { followLinks: false });
walker.on('file', function(root, stat, next) {
    // Add this file to the list of files
    root += '\\';
    var str = root.substr(folder.length + 1) + stat.name.substr(0, stat.name.length -5); //remove games\ and .json
    str = str.replace(/\\/g, "/");
    output += '\t"'+md5(str)+'": "'+str+'",\r\n';
    next();
});

walker.on('end', function() {
    output += '});';
    fs.writeFile("./js/services/constants.map.autogenerated.js", output);
});
